### ISSUE TITLE
can't export back to .cha

### ISSUE THREAD

**Issue by ebergelson** [christopheparisse/trjs#6]
Having no trouble exporting to .csv (line by line, one column per line), but while there is an optino to export to .cha it doesn't work/save/produce a file.

**Comment by christopheparisse** [comment]
Hello
I need to know which version you use and if this is the last version, then an example of a problem file, as on small tests at home this works on the last version.
It is the same for the English translation. I have made some progress, but I need to know the version, so that I know if I have forgotten some translation or if this was corrected in recent versions.
Best
PS also please tell me which computer system you are using.
Thank you.

**Comment by hggarrison** [comment]
I believe we are using verison 0.6.2. I downloaded it last week. I'm using the Mac OS X (10.7 +) download on my iMac, running Sierra.

**Comment by christopheparisse** [comment]
Yes the present version is 0.7.0
So there are a lot of bugs corrected as I’m working on this right now.
You will find it there: http://modyco.inist.fr/download/trjs-v0.7.0-macos.zip <http://modyco.inist.fr/download/trjs-v0.7.0-macos.zip> 
Very often I put the last correction on this page:
http://ct3.ortolang.fr/trjs/doku.php?id=doc:vbeta <http://ct3.ortolang.fr/trjs/doku.php?id=doc:vbeta>
So you should check it.
Hopefully I will have the time to do an English version for this page.
